### ISSUE TITLE
Question 7. - Find the birth date of the actor who played roles in First Wives Club and Searching for the Elephant.

### ISSUE THREAD

**Issue by conceptofmind** [stanfordnlp/dsp#11]
Hi all,

I am having difficulty validating the answer to the question: "Find the birth date of the actor who played roles in First Wives Club and Searching for the Elephant."

Do you know the name of the actor? I also brought this to the attention of Alby who was going to confirm.

Thank you,

Enrico

**Comment by okhat** [comment]
It's this guy: Lee Sang-woo

**Comment by conceptofmind** [comment]
> It's this guy: Lee Sang-woo

Ah. Thank you for the response.

These are different things: The First Wives Club (https://www.imdb.com/title/tt0116313/) and First Wive's Club (https://en.wikipedia.org/wiki/First_Wives%27_Club).
 
 Is there a place where you sampled your questions from? I would like to test with more than 13 cases.
 
 Thank you again for your great research.
 
 Enrico
