### ISSUE TITLE
Feature: add custom HF-models as LLMs

### ISSUE THREAD

**Issue by stalkermustang** [stanfordnlp/dsp#13]
Hi team, 
Do you have any plans for physical models, not only APIs? Can we serve LLM like Flan-T5-xxl and query it for free instead of the OpenAIs endpoint (as the only available option)?

According to [this](https://blog.vespa.ai/improving-text-ranking-with-few-shot-prompting/) blog post from Yahoo/Vespa search team, even the 3B model can deliver a performance boost while generating with a proper prompt. At the same time, it's available for individuals like me & community. 

IMO this change also requires code/structure refactoring, and it's not a one-evening task.

**Comment by okhat** [comment]
Appreciate your input, @stalkermustang ! Yes, we’re working on this. 

The effort is led by @santhnm2 and @amirziai

**Comment by okhat** [comment]
It probably doesn’t need a major refactor at the moment.. just appropriate wrappers

**Comment by stalkermustang** [comment]
@okhat Ok, please let me know if I can help with this integration / any other important staff.

**Comment by okhat** [comment]
@stalkermustang This particular integration seems under control, but would you like to help revamp our caching system? We're now using joblib but it's pretty basic and unreliable overall. Maybe we should have a redis server or a DB of some kind.

**Comment by varun-singh-work** [comment]
Hi Team , wanted to check by when do we plan to release the wrappers that would make it easier to use open source or custom/private LLM's ??

**Comment by okhat** [comment]
They are on the main branch!

**Comment by varun-singh-work** [comment]
would you be sharing/comitting a sample intro notebook for query HF models/LLMS similar to the one used with ChatGPT(intro.pynb) ??
