### ISSUE TITLE
Question 8:  Server down

### ISSUE THREAD

**Issue by ylchin** [stanfordnlp/dsp#17]
Hi I think the server for ColBERTv2 is down because when I try to run the programs with the RM using my own data set, the server doesn't connect, so I wanted to ask whether the server will be permanently down?

**Comment by okhat** [comment]
Hmm, looking into this

**Comment by okhat** [comment]
Seems working for us

**Comment by ylchin** [comment]
I'm not sure why but when I run the exact code from the .ipynb, it refuses to run and shows TimeoutError, no matter the size of the data fed into it.

The error message is as follows:
`Exception has occurred: ConnectTimeout
HTTPConnectionPool(host='ec2-44-228-128-229.us-west-2.compute.amazonaws.com', port=8893): Max retries exceeded with url: /api/search?query=What+genre+of+music+is+the+solo+artist+that+contributed+to+Real+Damage+a+variant+of%3F&k=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f478a1ad090>, 'Connection to ec2-44-228-128-229.us-west-2.compute.amazonaws.com timed out. (connect timeout=None)'))
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f478a1ad090>, 'Connection to ec2-44-228-128-229.us-west-2.compute.amazonaws.com timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='ec2-44-228-128-229.us-west-2.compute.amazonaws.com', port=8893): Max retries exceeded with url: /api/search?query=What+genre+of+music+is+the+solo+artist+that+contributed+to+Real+Damage+a+variant+of%3F&k=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f478a1ad090>, 'Connection to ec2-44-228-128-229.us-west-2.compute.amazonaws.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

  File "./dsp/modules/colbertv2.py", line 35, in colbertv2_get_request_v2
    res = requests.get(url, params=payload)
  File "./dsp/modules/colbertv2.py", line 46, in colbertv2_get_request_v2_wrapped
    return colbertv2_get_request_v2(*args, **kwargs)
  File "./dsp/modules/cache_utils.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "./dsp/modules/colbertv2.py", line 20, in __call__
    topk = colbertv2_get_request(self.url, query, k)
  File "./dsp/primitives/search.py", line 5, in retrieve
    passages = dsp.settings.rm(query, k=k)
  File "retrieve_read_gpt.py", line 51, in retrieve_then_read_QA
    passages = dsp.retrieve(question, k=1)
  File ". /dsp/evaluation/utils.py", line 63, in evaluate
    prediction = fn(question)
  File "./dsp/retrieve_read_gpt.py", line 62, in <module>
    evaluate(retrieve_then_read_QA, dev)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='ec2-44-228-128-229.us-west-2.compute.amazonaws.com', port=8893): Max retries exceeded with url: /api/search?query=What+genre+of+music+is+the+solo+artist+that+contributed+to+Real+Damage+a+variant+of%3F&k=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f478a1ad090>, 'Connection to ec2-44-228-128-229.us-west-2.compute.amazonaws.com timed out. (connect timeout=None)'))
`

**Comment by okhat** [comment]
Are you still facing this issue? The server seems totally fine from our end

**Comment by ylchin** [comment]
yes...

**Comment by okhat** [comment]
Okay. Does this link work for you?

http://ec2-44-228-128-229.us-west-2.compute.amazonaws.com:8893/api/search?query=what%20is%20the%20capital%20of%20australia

**Comment by ylchin** [comment]
yes, this link works

**Comment by okhat** [comment]
Awesome! Well, then, the queries issued in the code are simply get requests like this. Can you share a minimal example that doesn’t work?

**Comment by ylchin** [comment]
in the intro.ipynb notebook, i use the exact code as program 2, with the exception of the train and dev sets, but the colbert server doesnt connect. the timeout error keeps popping out, and when i try to open the server in the browsers it keeps saying "This site can’t be reached. ec2-44-228-128-229.us-west-2.compute.amazonaws.com refused to connect."

**Comment by okhat** [comment]
I've tested the server from the notebook just fine. What do you get for the following cell:

```
rm("world war II")
```

Does it output a ranking?

**Comment by ylchin** [comment]
No it doesnt, a timeout error and connection error appears.

**Comment by okhat** [comment]
I see. Well, I have to guess that your IP address is blocked. Can you try from a different IP address or with a VPN?
