### ISSUE TITLE
Cannot configure DSP to work with my openai api key

### ISSUE THREAD

**Issue by akshaydevml** [stanfordnlp/dsp#20]
Getting this error, '[openai.error.InvalidRequestError: Engine not found](https://stackoverflow.com/questions/71597547/openai-error-invalidrequesterror-engine-not-found)', when I try and change dsp's lm configuration to my instance of openai's api key

**Comment by okhat** [comment]
Hmm either openai is down or you changed the model to an incorrect name?

**Comment by okhat** [comment]
Is this resolved? Feel free to share a minimal example to reproduce (but remember to remove your API key from it)

**Comment by akshaydevml** [comment]
Gettng an error, 'AuthenticationError: Incorrect API key provided', even though the key is correct

**Comment by okhat** [comment]
Okay. Can you restart the notebook, set the key before any other cells are executed and try again?

**Comment by akshaydevml** [comment]
Tried, still the same error :/

**Comment by okhat** [comment]
The LM wrapper in DSP is fairly thin. If you’re getting this error in DSP, are you also seeing the error when directly using openai?

**Comment by akshaydevml** [comment]
I regenerated my openai api key, it's working now.
