### ISSUE TITLE
the intro.ipynb colab fails

### ISSUE THREAD

**Issue by IQ17** [stanfordnlp/dsp#26]
hi, it seems that the colab fails to install the dsp-ml.

`
try: # When on google Colab, let's clone the notebook so we download the cache.
    import google.colab 
    !git -C dsp/ pull || git clone https://github.com/stanfordnlp/dsp
except: pass

!pip install -U dsp-ml

Already up to date.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting dsp-ml
  Using cached dsp-ml-0.1.4.tar.gz (18 kB)
  Preparing metadata (setup.py) ... done
Collecting backoff
  Using cached backoff-2.2.1-py3-none-any.whl (15 kB)
Requirement already satisfied: joblib in /usr/local/lib/python3.9/dist-packages (from dsp-ml) (1.2.0)
Collecting jupyter
  Using cached jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)
Collecting openai
  Using cached openai-0.27.1.tar.gz (57 kB)
  Installing build dependencies ... done
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

`

**Comment by okhat** [comment]
Some openai upgrade issue. 

Do
pip install -U pip 
First.

**Comment by okhat** [comment]
Just added this to the notebook itself. Should be fixed now!

**Comment by okhat** [comment]
Feel free to re-open if there are other issues.
