### ISSUE TITLE
branch primitive not found

### ISSUE THREAD

**Issue by ylchin** [stanfordnlp/dsp#29]
hi, i would like to inquire about the primitive branch that is mentioned in the research paper. i don't think i am able to find it in any of the codes in the repo...

also, i would also like to know if there is any way we could see what are the direct requests to the api

**Comment by okhat** [comment]
Thanks for asking, @ylchin ! We haven't merged the branch primitive yet. As we note in the paper, some components of it are work in progress (mainly concurrency).
