### ISSUE TITLE
missing __init__.py in dsp/evaluation.py

### ISSUE THREAD

**Issue by cbrew** [stanfordnlp/dsp#5]
needed in order to let Python know that the evaluation directory is a package. Can be empty.

Demo works beautifully even on a laptop.

**Comment by okhat** [comment]
Ah, thanks! Will merge if you have a PR

**Comment by cbrew** [comment]
doing PR

**Comment by cbrew** [comment]
PR is available

**Comment by okhat** [comment]
Thanks a lot, Chris!
