### ISSUE TITLE
About the colbertV2 search server

### ISSUE THREAD

**Issue by webdxq** [stanfordnlp/dsp#56]
Hi, Did you split the Wikipedia (Dec 2018) doc to small passages? Could you tell more about the colbertV2 model you use? The colbert end-to-end model or re-rank model? I was wondering why the search result  is shorter than the real wiki page.

**Comment by okhat** [comment]
We're using the DPR wikipedia splits (100 words per paragraph). This is very popular in the retrieval-based open-QA world.

https://huggingface.co/datasets/wiki_dpr

**Comment by webdxq** [comment]
Thank you for your reply!
