### ISSUE TITLE
Documentation to help support a custom data set

### ISSUE THREAD

**Issue by davidwynter** [stanfordnlp/dsp#59]
I am setting up an experiment to try DSP using a custom dataset. This consists of 2200 customer support conversations and 140 document articles, used in finding answers to customer questions. We curate this data and add which parts of conversations are useful and whether a conversation part is a preliminary follow up question from the support agent and the subsequent answer from the customer. This is very common, where the agent needs more information to answer the initial customer question. We also add a list of questions that are answered by an article to provide context. 

What would be useful in the documentation is a walkthrough of how to support such a custom dataset. Some of the considerations would be:

1. How we condition our dataset to suit the Example inputs required by DSP. It is fairly clear that the preliminary questions and answers lend themselves to CoT approach, but it is not clear how this relates to the DSP Examples required.
2. Our final answers often have multiple steps to be followed by the customer. Also a lot of intermediate answers are quite long. All your examples have very short answers. It is not clear if our dataset suits DSP as a consequence of this difference.
3. We would need to train Colbert V2 on our data. It is not clear where we can do the training on a service supporting Colbert v2
4. What specification of PC we would need to run the Colbert V2 inference for RM. I have a 8 core 16GB RAM mini server available, but do not know if it would be adequate.
5. It would also be interesting to see if there is much difference in performance replacing RM with a simpler mechanism such a FAISS.

Thank you for the great work so far!

**Comment by davidwynter** [comment]
To answer my first question convqa_program mentioned in section 3.4 of the paper looks like it accommodates this requirement.

**Comment by okhat** [comment]
Hey @davidwynter ,

Please see here for indexing your own data for retrieval: https://github.com/stanford-futuredata/ColBERT#running-a-lightweight-colbertv2-server

Before you launch the server, use the ColBERT intro notebook (or the Overview in the ColBERT README) to index your collection

In principle, you shouldn't need to train a new retriever. You can usually use the one we provide (depending on licensing at least; it's trained on MS MARCO, the dataset itself is for non-commercial research use).
