### ISSUE TITLE
dsp.generate self-consistency

### ISSUE THREAD

**Issue by tsavage6001** [stanfordnlp/dsp#60]
I am using dsp.generate for question answer with self-consistency.  When I use dsp.generate with the following code I get varying numbers of completions (sometimes the full n and sometimes less, sometimes even 1).  Would you know why I don't get the full n?

code:
example, completions = dsp.generate(qa_template_with_CoT_context_diag, n=23, temperature=0.7)(example, stage='qa')

**Comment by tsavage6001** [comment]
Nevermind, found that it was just with large inputs it cuts off

**Comment by okhat** [comment]
OpenAI seems timo have become less reliable at large n recently — it wasn’t so before
