### ISSUE TITLE
ColBERTv2 ec2 instance

### ISSUE THREAD

**Issue by lucifermorningstar1305** [stanfordnlp/dsp#70]
Hi, 

I am trying to query the ColBERT v2 ec2 instance in the notebook but have trouble getting a response from it. Is it still running?

**Comment by okhat** [comment]
See the readme. New link.

**Comment by lucifermorningstar1305** [comment]
My bad; I'm sorry I couldn't notice it at first. Thanks for the help and prompt reply :smile:
