### ISSUE TITLE
Is it legal to use OpenAI output to compile a smaller model?

### ISSUE THREAD

**Issue by jjmachan** [stanfordnlp/dsp#71]
The compilation step is very neat and I love the DSP paradym and was planning to implement it internally. But we not sure about a legal consideration. According to openai's terms of service

> (iii) use output from the Services to develop models that compete with OpenAI;

is not allowed.

Does this mean if I compile a model based on the outputs from GPT-4 to fine-tune a smaller opensource model that is used internally or used to power a product that is in no way competing with OpenAI fine? or is that Illegal as well?

**Comment by okhat** [comment]
Thanks for the question! We cannot provide legal advice. That said, our goal in DSP is to advance research into LLMs and not to compete with OpenAI.

For products, I can say two things:

First, OpenAI themselves have notebooks on how to train "curie" models on the output of Davinci: https://github.com/openai/openai-cookbook/blob/main/examples/fine-tuned_qa/olympics-3-train-qa.ipynb  —  You may consider whether you want to do something similar. Our compiler notebook trains an "ada" model. I think OpenAI will release more finetuning offerings very soon, which may be supported in our compiler.

Second, if you want to use a local open model, whether that qualifies as competing with OpenAI is (at most) unclear to me. Especially if the model you produce isn't the main service you're providing, but simply a component in your application. If you are to provide an API for your model as an LLM, then you're probably competing directly with OpenAI.

Again, none of this is legal advice. DSP is a research project. I hope these pointers help!
