### ISSUE TITLE
Can we use Azure Coginitive Search to replace Colbert based RM

### ISSUE THREAD

**Issue by hasalams** [stanfordnlp/dsp#74]
In my use case, I have data indexed on Azure cognitive search. 

How can I leverage DSP capabilities with such data?

In the DSP intro notebook, I notice the following Wrapper for the ColBERTv2 Retrieval. 

`rm = dsp.ColBERTv2(url=colbert_server)`

How can I have a new wrapper which is compatible with Azure cognitive search? Is it a functionality you plan to include in the future? Thank you.

**Comment by okhat** [comment]
It should be very simple to add that as a rapper that behaves like the colbert retriever. If you add that as a PR I’m happy to merge it!

**Comment by hasalams** [comment]
> It should be very simple to add that as a wrapper that behaves like the colbert retriever. If you add that as a PR I’m happy to merge it!

Thanks for the prompt reply. 
I will try to implement and test it first. Will do the PR once done. Thanks again.

**Comment by hasalams** [comment]
Added wrapper class and tested with my Azure Cognitive Search index
I added a PR. Please check. Thanks
