### ISSUE TITLE
What is the best way to select train questions?

### ISSUE THREAD

**Issue by hasalams** [stanfordnlp/dsp#77]
Suppose I have a question, which require the answer to be generated by examining multiple sections of a document. 

What kind of training questions should I include?

Does it need to be a mix of direct answer questions and multi section examine ones?

Any best practices to prepare the training Q/A pairs, especially when using with Program5 on intro notebook. Thanks in advance.

**Comment by detaos** [comment]
In general, KNN (dsp.knn) selection will yield good results, since it chooses the most similar demonstration questions.

**Comment by hasalams** [comment]
> In general, KNN (dsp.knn) selection will yield good results, since it chooses the most similar demonstration questions.

thanks for the response.
