### ISSUE TITLE
colbert Wikipedia server down

### ISSUE THREAD

**Issue by seanjaffeg** [stanfordnlp/dsp#79]
api requests to  'http://ec2-35-87-71-196.us-west-2.compute.amazonaws.com:8893/api/search ' are yielding Connection errors and requests to 'http://ec2-44-228-128-229.us-west-2.compute.amazonaws.com' are timing out. I was wondering if the Wikipedia Colbert-V2 server (at whichever address is correct) is down.

**Comment by okhat** [comment]
Seems fine, but please don’t overload it. If it times out, use it later. 

http://ec2-35-87-71-196.us-west-2.compute.amazonaws.com:8893/api/search?query=Who%20has%20got%20Nobel%20Prize%20in%20economics%20from%20India

**Comment by Gy915** [comment]
I try to use:

requests.get(url, params=payload, timeout=10)
url = 'http://index.contextual.ai:8893/api/search'
payload={'k': 20, 'query': 'Kansas Song'}
and receive 502.

**Comment by okhat** [comment]
```python
import dsp
dsp.settings.configure(rm=dsp.ColBERTv2(url='[http://index.contextual.ai:8893/api/search](https://t.co/mUlEbhdULE)'))

dsp.retrieve('when was stanford founded', k=1)
```

**Comment by nvbkdw** [comment]
ColBERT server seems like is down. 

```
% curl -v 'http://index.contextual.ai:8893/api/search?query=Who%20has%20got%20Nobel%20Prize%20in%20economics%20from%20India'
*   Trying 35.209.35.95:8893...
* connect to 35.209.35.95 port 8893 failed: Operation timed out
* Failed to connect to index.contextual.ai port 8893 after 75010 ms: Couldn't connect to server
* Closing connection 0
curl: (28) Failed to connect to index.contextual.ai port 8893 after 75010 ms: Couldn't connect to server
```

Would you mind to share the index file on hugging face for people to run ColBERT server locally?

**Comment by okhat** [comment]
@nvbkdw We'll look into why it's down but please check the intro.ipynb notebook, it has a smaller index (first paragraph of wiki 2017) that you can use

**Comment by MMesgar** [comment]
The server is down again?
