### ISSUE TITLE
How to remove multiple use of demonstrate stage to save LLM calls

### ISSUE THREAD

**Issue by hasalams** [stanfordnlp/dsp#80]
I am using the program 5 on intro notebook for an experiment. 

I have multiple 100 of questions to get answers. I am using 5 train questions to demonstrate.

I notice that for each question, the demonstrate stage is annotating answers. Can this repeated task be avoided to save LLM calls in demonstrate stage? 

Can we use the demonstrate once, and use the demonstration in other questions as well?

Thanks.

**Comment by okhat** [comment]
It’s easy to make the change by rearranging your code. 

That said, when the LM is called a second time on some input, it’s free. It’s cached.

**Comment by hasalams** [comment]
thanks for the prompt response.
